---

- name: Add ipfs systemd unit file
  template:
    src: systemd_ipfs.service.j2
    dest: /etc/systemd/system/{{ ipfs_systemd_unit_name }}.service
    mode: 0644
    owner: root
    group: root
  notify:
    - reload systemd
  when: ipfs_create_systemd_unit

- name: Start and Enable ipfs service
  service:
    name: "{{ ipfs_systemd_unit_name }}"
    state: started
    enabled: "{{ ipfs_service_onboot }}"
