---
# handlers file for ipfs

- name: restart ipfs
  service:
    name: "{{ ipfs_systemd_unit_name }}"
    state: restarted
  become: true

- name: reload systemd
  # systemd module not available before ansible version 2.2
  #systemd: daemon_reload=yes name=docker
  # work around - use command
  command: systemctl daemon-reload
  become: true

# currently, we can only restart all ipfs services because we defined them dynamically
- name: restart ipfs multi
  service:
    name: "ipfs-{{ item.key }}"
    state: restarted
  with_dict: "{{ ipfs_nodes }}"
  become: true
